version: 1.0.{build}
image: Visual Studio 2017

configuration:
- Debug
- Release

platform: Any CPU

test: on

build_script:
- for /f "tokens=1,* delims=-" %%a in ('"git describe --long --tags --match v*"') do set version_suffix=%%b
- msbuild /t:Restore,Rebuild /p:RestorePackagesConfig=true /p:VersionSuffix="%version_suffix%-%CONFIGURATION%" /p:Platform="%PLATFORM%" /p:Configuration="%CONFIGURATION%" Toxy.sln
- msbuild /t:Restore,Rebuild /p:RestorePackagesConfig=true /p:VersionSuffix="%version_suffix%-%CONFIGURATION%" /p:Platform="%PLATFORM%" /p:Configuration="%CONFIGURATION%" Toxy.Tools\Toxy.Tools.sln

after_build:
- ps: $env:PRODUCT_VERSION=(Get-Command "$env:APPVEYOR_BUILD_FOLDER\Toxy.Tools\ToxyExtract\bin\$env:CONFIGURATION\net40\ToxyExtract.exe").FileVersionInfo.ProductVersion

artifacts:
- path: Toxy.Tools\ToxyExtract\bin\$(configuration)\net40
  name: ToxyExtract_$(PRODUCT_VERSION)
